# Kafka
kafka.broker=localhost:9092
kafka.topic.actor=ActorTopic
kafka.topic.news=NewsTopic

# Cassandra
cassandra.host=localhost
cassandra.port=9042
cassandra.keyspace=imdb_keyspace2

# Spark
spark.batch.duration.ms=20000
spark.checkpoint.dir=/tmp/spark-checkpoint

# CSV paths
csv.actors=src/main/resources/actor/mostPopularCelebs.csv
csv.movies=src/main/resources/movie/knownMovies.csv
csv.topRated=src/main/resources/movie/topRatedMovies.csv
csv.actorMovies=src/main/resources/movie_actor/actorKnownFor.csv
stopwords.path=src/main/resources/stopwords.txt